// Kenney CC0 sources, edits and hashes: docs/audio/sfx-sources.json.
// Literal paths allow the production ownership audit to check every sample.
const FILES = Object.freeze({
  'confirm': './assets/audio/sfx/kenney-v1/confirm.wav',
  'pulse-1': './assets/audio/sfx/kenney-v1/pulse-1.wav',
  'pulse-2': './assets/audio/sfx/kenney-v1/pulse-2.wav',
  'blade-1': './assets/audio/sfx/kenney-v1/blade-1.wav',
  'blade-2': './assets/audio/sfx/kenney-v1/blade-2.wav',
  'halo': './assets/audio/sfx/kenney-v1/halo.wav',
  'needle': './assets/audio/sfx/kenney-v1/needle.wav',
  'warrant': './assets/audio/sfx/kenney-v1/warrant.wav',
  'turret': './assets/audio/sfx/kenney-v1/turret.wav',
  'enemy-shot': './assets/audio/sfx/kenney-v1/enemy-shot.wav',
  'rail': './assets/audio/sfx/kenney-v1/rail.wav',
  'hit-1': './assets/audio/sfx/kenney-v1/hit-1.wav',
  'hit-2': './assets/audio/sfx/kenney-v1/hit-2.wav',
  'player-hit': './assets/audio/sfx/kenney-v1/player-hit.wav',
  'kill': './assets/audio/sfx/kenney-v1/kill.wav',
  'dash': './assets/audio/sfx/kenney-v1/dash.wav',
  'explosion': './assets/audio/sfx/kenney-v1/explosion.wav',
  'shield': './assets/audio/sfx/kenney-v1/shield.wav',
  'shield-hit': './assets/audio/sfx/kenney-v1/shield-hit.wav',
  'emp': './assets/audio/sfx/kenney-v1/emp.wav',
  'arc': './assets/audio/sfx/kenney-v1/arc.wav',
  'gate': './assets/audio/sfx/kenney-v1/gate.wav',
  'boss-intro': './assets/audio/sfx/kenney-v1/boss-intro.wav',
  'boss-break': './assets/audio/sfx/kenney-v1/boss-break.wav',
  'boss-death': './assets/audio/sfx/kenney-v1/boss-death.wav',
  'warning': './assets/audio/sfx/kenney-v1/warning.wav',
  'failure': './assets/audio/sfx/kenney-v1/failure.wav',
  'upgrade': './assets/audio/sfx/kenney-v1/upgrade.wav',
  'collect': './assets/audio/sfx/kenney-v1/collect.wav',
  'victory': './assets/audio/sfx/kenney-v1/victory.wav',
  'click': './assets/audio/sfx/kenney-v1/click.wav',
  'hover': './assets/audio/sfx/kenney-v1/hover.wav',
  'close': './assets/audio/sfx/kenney-v1/close.wav',
  'denied': './assets/audio/sfx/kenney-v1/denied.wav',
  'build': './assets/audio/sfx/kenney-v1/build.wav',
  'select': './assets/audio/sfx/kenney-v1/select.wav',
  'sell': './assets/audio/sfx/kenney-v1/sell.wav',
  'repair': './assets/audio/sfx/kenney-v1/repair.wav',
});
const cue = (ids, gain, fallback, cooldownMs) => Object.freeze({
  paths: Object.freeze(ids.map(id => FILES[id])), gain, fallback, cooldownMs,
});
export const SFX_SAMPLES = Object.freeze({
  start: cue(["confirm"], 0.24),
  shoot: cue(["pulse-1","pulse-2"], 0.24),
  sword: cue(["blade-1","blade-2"], 0.35, 'rail', 90),
  mikaShot: cue(["halo"], 0.21, 'arc', 90),
  vesperShot: cue(["needle"], 0.23, 'rail', 90),
  noxShot: cue(["warrant"], 0.23, 'rail', 110),
  towerShot: cue(["turret"], 0.18),
  enemyShot: cue(["enemy-shot"], 0.16),
  rail: cue(["rail"], 0.25),
  enemyHit: cue(["hit-1","hit-2"], 0.2),
  playerHit: cue(["player-hit"], 0.46),
  kill: cue(["kill"], 0.16),
  dash: cue(["dash"], 0.32),
  explosion: cue(["explosion"], 0.34),
  shield: cue(["shield"], 0.28),
  shieldHit: cue(["shield-hit"], 0.26),
  emp: cue(["emp"], 0.36),
  arc: cue(["arc"], 0.18),
  spawnGate: cue(["gate"], 0.2),
  boss: cue(["boss-intro"], 0.38),
  bossBreak: cue(["boss-break"], 0.37),
  bossDeath: cue(["boss-death"], 0.46),
  bossTelegraph: cue(["warning"], 0.48),
  patternFail: cue(["failure"], 0.43),
  enemyAlert: cue(["warning"], 0.24),
  alert: cue(["warning"], 0.38),
  counter: cue(["shield-hit"], 0.4),
  merge: cue(["upgrade"], 0.36),
  collect: cue(["collect"], 0.14),
  core: cue(["confirm"], 0.37),
  capture: cue(["failure"], 0.36),
  analysis: cue(["upgrade"], 0.27),
  reward: cue(["confirm"], 0.28),
  upgrade: cue(["upgrade"], 0.3),
  victory: cue(["victory"], 0.38),
  click: cue(["click"], 0.2),
  uiHover: cue(["hover"], 0.09),
  uiConfirm: cue(["confirm"], 0.24),
  uiClose: cue(["close"], 0.2),
  denied: cue(["denied"], 0.28),
  build: cue(["build"], 0.3),
  defenseSelect: cue(["select"], 0.17),
  defenseBuild: cue(["build"], 0.3),
  defenseUpgrade: cue(["upgrade"], 0.3),
  defenseSell: cue(["sell"], 0.24),
  defenseWave: cue(["warning"], 0.38),
  defenseClear: cue(["confirm"], 0.34),
  defenseBreach: cue(["player-hit"], 0.45),
  defenseAbility: cue(["emp"], 0.34),
  defenseRepair: cue(["repair"], 0.3),
  defenseEliteDown: cue(["boss-break"], 0.28),
  defenseDefeat: cue(["failure"], 0.4),
});
export const SFX_SAMPLE_PATHS = Object.freeze([...new Set(Object.values(SFX_SAMPLES).flatMap(cue => cue.paths))]);
