export const GAME_WIDTH = 1280;
export const GAME_HEIGHT = 720;
export const ZONE_WIDTH = GAME_WIDTH / 2;
export const ZONE_HEIGHT = GAME_HEIGHT / 2;
export const RUN_DURATION = 300;

export const REGIONS = [
  {
    id: 0,
    code: "NORTH-01",
    name: "CRYO RELAY",
    korean: "빙결 중계소",
    accent: "#63efff",
    dark: "#071a25",
    glow: "rgba(50, 214, 255, .18)",
    x: 0,
    y: 0,
    width: ZONE_WIDTH,
    height: ZONE_HEIGHT,
    hero: "vanguard",
    motif: "grid",
  },
  {
    id: 1,
    code: "EAST-02",
    name: "EMBER FORGE",
    korean: "용광 제련소",
    accent: "#ffad42",
    dark: "#231408",
    glow: "rgba(255, 130, 42, .18)",
    x: ZONE_WIDTH,
    y: 0,
    width: ZONE_WIDTH,
    height: ZONE_HEIGHT,
    hero: "gunner",
    motif: "forge",
  },
  {
    id: 2,
    code: "WEST-03",
    name: "NEON ARCHIVE",
    korean: "네온 기록고",
    accent: "#ba7dff",
    dark: "#160d25",
    glow: "rgba(165, 76, 255, .18)",
    x: 0,
    y: ZONE_HEIGHT,
    width: ZONE_WIDTH,
    height: ZONE_HEIGHT,
    hero: "arcanist",
    motif: "archive",
  },
  {
    id: 3,
    code: "SOUTH-04",
    name: "VERDANT VAULT",
    korean: "생체 보존고",
    accent: "#76f09c",
    dark: "#0a2019",
    glow: "rgba(72, 222, 135, .17)",
    x: ZONE_WIDTH,
    y: ZONE_HEIGHT,
    width: ZONE_WIDTH,
    height: ZONE_HEIGHT,
    hero: "warden",
    motif: "bio",
  },
];

export const HERO_ARCHETYPES = {
  vanguard: {
    name: "AEGIS",
    role: "PULSE VANGUARD",
    sprite: "player",
    hp: 145,
    speed: 164,
    radius: 17,
    damage: 31,
    fireInterval: 0.3,
    bulletSpeed: 600,
    range: 270,
    projectile: "pulse",
    color: "#63efff",
  },
  gunner: {
    name: "ROOK",
    role: "FORGE GUNNER",
    sprite: "suppressor",
    hp: 125,
    speed: 152,
    radius: 18,
    damage: 14,
    fireInterval: 0.43,
    bulletSpeed: 560,
    range: 235,
    projectile: "scatter",
    color: "#ffad42",
  },
  arcanist: {
    name: "NYX",
    role: "ARC WEAVER",
    sprite: "hunter",
    hp: 112,
    speed: 178,
    radius: 16,
    damage: 27,
    fireInterval: 0.56,
    bulletSpeed: 0,
    range: 255,
    projectile: "chain",
    color: "#ba7dff",
  },
  warden: {
    name: "MOSS",
    role: "BIO WARDEN",
    sprite: "brute",
    hp: 195,
    speed: 130,
    radius: 23,
    damage: 43,
    fireInterval: 0.72,
    bulletSpeed: 470,
    range: 220,
    projectile: "heavy",
    color: "#76f09c",
    regen: 0.7,
  },
};

export const ENEMY_TYPES = {
  raider: {
    name: "RAIDER",
    hp: 24,
    speed: 88,
    radius: 12,
    damage: 8,
    gold: 5,
    sprite: "hunter",
  },
  shooter: {
    name: "MARKSMAN",
    hp: 46,
    speed: 58,
    radius: 14,
    damage: 10,
    gold: 9,
    sprite: "suppressor",
    ranged: true,
  },
  brute: {
    name: "BREAKER",
    hp: 118,
    speed: 38,
    radius: 22,
    damage: 18,
    gold: 17,
    sprite: "brute",
  },
  boss: {
    name: "SECTOR WARDEN",
    hp: 760,
    speed: 31,
    radius: 34,
    damage: 23,
    gold: 90,
    sprite: "brute",
    ranged: true,
    boss: true,
  },
};

export const SHOP_ITEMS = [
  {
    id: "arsenal",
    name: "WEAPON CORE",
    korean: "무기 코어",
    tag: "공격 강화",
    description: "선택 영웅의 공격력이 24% 증가합니다.",
    baseCost: 38,
    max: 5,
    icon: "Crosshair",
  },
  {
    id: "firerate",
    name: "REFLEX SERVO",
    korean: "반응 서보",
    tag: "공격 강화",
    description: "선택 영웅의 공격 주기가 14% 빨라집니다.",
    baseCost: 42,
    max: 4,
    icon: "Lightning",
  },
  {
    id: "vitality",
    name: "AEGIS PLATE",
    korean: "강화 장갑",
    tag: "방어 강화",
    description: "최대 체력과 현재 체력이 30 증가합니다.",
    baseCost: 48,
    max: 4,
    icon: "ShieldChevron",
  },
  {
    id: "regen",
    name: "NANO REPAIR",
    korean: "나노 수복",
    tag: "생존 강화",
    description: "초당 체력 재생이 0.45 증가합니다.",
    baseCost: 52,
    max: 4,
    icon: "Heartbeat",
  },
  {
    id: "drone",
    name: "WINGMAN DRONE",
    korean: "윙맨 드론",
    tag: "자동 스킬",
    description: "보조 드론이 영웅을 따라다니며 자동 사격합니다.",
    baseCost: 72,
    max: 3,
    icon: "Drone",
  },
  {
    id: "sentry",
    name: "SENTRY NODE",
    korean: "센트리 노드",
    tag: "설치형 스킬",
    description: "Q로 설치하는 자동 센트리를 해금·강화합니다.",
    baseCost: 64,
    max: 3,
    icon: "Broadcast",
  },
  {
    id: "emp",
    name: "EMP PYLON",
    korean: "EMP 파일런",
    tag: "설치형 스킬",
    description: "E로 설치하는 감속·방해 파일런을 해금·강화합니다.",
    baseCost: 78,
    max: 3,
    icon: "WaveSine",
  },
  {
    id: "medkit",
    name: "FIELD MEDKIT",
    korean: "전투 구급팩",
    tag: "소모품",
    description: "선택 영웅의 체력을 즉시 55 회복합니다.",
    baseCost: 28,
    consumable: true,
    icon: "FirstAid",
  },
  {
    id: "barrier",
    name: "BARRIER CELL",
    korean: "방벽 셀",
    tag: "소모품",
    description: "선택 영웅에게 35의 임시 방어막을 부여합니다.",
    baseCost: 34,
    consumable: true,
    icon: "ShieldCheck",
  },
  {
    id: "teamRepair",
    name: "NETWORK REPAIR",
    korean: "전선 동기화 수복",
    tag: "공유 보급",
    description: "생존한 모든 영웅의 체력을 26 회복합니다.",
    baseCost: 76,
    consumable: true,
    icon: "UsersThree",
  },
];

export function getShopItemCost(item, level = 0) {
  if (item.consumable) return item.baseCost;
  return Math.round(item.baseCost * (1 + level * 0.56));
}

export function formatTime(seconds) {
  const safe = Math.max(0, Math.ceil(seconds));
  return `${String(Math.floor(safe / 60)).padStart(2, "0")}:${String(safe % 60).padStart(2, "0")}`;
}
